## Full path: /opt/awx-install/awx/installer/roles/image_build/templates
FROM {{ web_image }}:{{ awx_version }}
USER 0
RUN sudo yum -y remove nginx
RUN sudo pip install MinIO
WORKDIR /bin
RUN curl -O https://releases.hashicorp.com/vault/1.1.2/vault_1.1.2_linux_amd64.zip
RUN unzip vault_1.1.2_linux_amd64.zip
RUN yum install jq -y
USER 1000
EXPOSE 8052
CMD /usr/bin/launch_awx_task.sh
